### ISSUE TITLE
Problem with the screen

### ISSUE THREAD

**Issue by Vaxela** [yasirkula/Unity360ScreenshotCapture#4]
Hi i'am developing virtual visit and i have this problem when i take 360 screens
Unity 2018.1.5f1
I have this effects with 360 :
![360render](https://user-images.githubusercontent.com/32814462/42497903-18edcf4a-842b-11e8-8986-4fa6a0e4fe44.jpeg)

Normal screen :
![screen_3840x2160_2018-07-10_10-22-44](https://user-images.githubusercontent.com/32814462/42497962-4516d328-842b-11e8-8821-a2a73343d3bd.jpg)

PostProcessing 2.0.7 

And screen with just a camera and your script rendertest

![360render](https://user-images.githubusercontent.com/32814462/42498396-5fbe3558-842c-11e8-8b4d-b5796b6a687f.jpeg)

**Comment by yasirkula** [comment]
I believe we are talking about the black floor texture (correct me if I am wrong). Honestly, I can't see any reason for it to happen, especially when rendered with a camera without any post-processing effects.

The thing is, I actually have no control over how the 360 image looks; the image comes from Unity's Camera.RenderToCubemap function. I just inject XMP metadata to it so that it can be recognized as a photosphere image. There is not much I can do to help with artifacts in the image.

**Comment by Vaxela** [comment]
Yep im talking about that, ok no problem , i will fix that, have good days !
