### ISSUE TITLE
Can the rendered panorama match the x-axis of the camera rotation?

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/Unity360ScreenshotCapture#6]
![image](https://user-images.githubusercontent.com/50401776/63632353-16534d80-c667-11e9-8210-d47923cba082.png)
I changed the angle of the camera, but at most I can only render such a picture, can I match the x of the camera, for example,
![image](https://user-images.githubusercontent.com/50401776/63632390-98dc0d00-c667-11e9-9c7d-9de007ee853d.png)
![image](https://user-images.githubusercontent.com/50401776/63632393-a6919280-c667-11e9-8b6f-ff89565b8774.png)

**Comment by ShenKang4181** [comment]
Can you match the x of the camera?

**Comment by yasirkula** [comment]
It could be possible. You can check how the [faceCameraDirection](https://github.com/yasirkula/Unity360ScreenshotCapture/blob/36d7f48fc0797dc7e2679a446b5b7a272f80fe09/Plugins/Simple360Render/I360Render.cs#L47) parameter is [passed to the shader](https://github.com/yasirkula/Unity360ScreenshotCapture/blob/36d7f48fc0797dc7e2679a446b5b7a272f80fe09/Plugins/Simple360Render/Resources/EquirectangularConverter.shader#L42) and replicate the same effect for the X angle. I haven't tested it and I don't recommend doing so since all photosphere images out there have a 0 x-rotation. User can then scroll the image if they want.

**Comment by ShenKang4181** [comment]
------------------ 原始邮件 ------------------
发件人: "Süleyman Yasir KULA"<notifications@github.com>; 
发送时间: 2019年8月24日(星期六) 下午3:16
收件人: "yasirkula/Unity360ScreenshotCapture"<Unity360ScreenshotCapture@noreply.github.com>; 
抄送: "申康康"<1284784181@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yasirkula/Unity360ScreenshotCapture] Can the rendered panoramamatch the x-axis of the camera rotation? (#6)




关闭＃6。
 
- 
您收到此消息是因为您创作了该帖子。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by ShenKang4181** [comment]
Teşekkür ederim




------------------ 原始邮件 ------------------
发件人: "Süleyman Yasir KULA"<notifications@github.com>; 
发送时间: 2019年8月24日(星期六) 下午3:16
收件人: "yasirkula/Unity360ScreenshotCapture"<Unity360ScreenshotCapture@noreply.github.com>; 
抄送: "申康康"<1284784181@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [yasirkula/Unity360ScreenshotCapture] Can the rendered panoramamatch the x-axis of the camera rotation? (#6)




It could be possible. You can check how the faceCameraDirection parameter is passed to the shader and replicate the same effect for the X angle. I haven't tested it and I don't recommend doing so since all photosphere images out there have a 0 x-rotation. User can then scroll the image if they want.
